[package]
name = "mocikashield"
version = "1.4.0-alpha.2"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "mocikashield"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
zstd = { workspace = true }
chacha20poly1305 = { workspace = true }
hkdf = { workspace = true }
sha2 = { workspace = true }
